"""Builds docs/SECURITY_REPORT.md from real runs: test suite, mutation check, benchmark, Java vectors.

Usage: python tools/security_report.py
"""
from __future__ import annotations

import datetime
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(cmd: list[str], cwd: Path = ROOT, timeout: int = 900) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)


def main() -> None:
    tests = run([sys.executable, "-m", "pytest", "-v", "-p", "no:cacheprovider", "tests"])
    rows = re.findall(r"tests/(\w+)\.py::(\w+) (PASSED|FAILED|ERROR)", tests.stdout)
    summary = tests.stdout.strip().splitlines()[-1] if tests.stdout.strip() else "no output"
    mutation = run([sys.executable, "tools/mutation_check.py"])
    bench = run([sys.executable, "tools/benchmark.py", "300"])
    java = "Java not available on this machine."
    core = ROOT / "java" / "wwgateway-verifier-core"
    # On Windows, which("mvn") can return Maven's extensionless Unix script (WinError 193): prefer mvn.cmd.
    mvn = (shutil.which("mvn.cmd") if sys.platform == "win32" else None) or shutil.which("mvn")
    if mvn:
        jv = run([mvn, "-B", "verify"], cwd=ROOT / "java")
        lines = [line.removeprefix("[INFO] ").removeprefix("[ERROR] ") for line in jv.stdout.splitlines()
                 if re.search(r"Tests run: \d+.* -- in |vectors passed|BUILD (SUCCESS|FAILURE)", line)]
        java = (f"`mvn -B verify` (verifier core, Spring Boot starter, example): **{'PASSED' if jv.returncode == 0 else 'FAILED'}**"
                "\n\n```\n" + "\n".join(lines) + "\n```")
        if jv.returncode != 0:
            java += "\n\n```\n" + jv.stdout[-3000:] + "\n```"
    elif shutil.which("java"):
        build = Path("/tmp/wwg-java-build")
        sources = [str(p) for p in (core / "src" / "main").rglob("*.java")] + [str(core / "src/test/java/com/wwgateway/verifier/VectorSuite.java")]
        compiled = run(["java", str(ROOT / "tools" / "Javac.java"), "-d", str(build), *sources])
        if compiled.returncode == 0:
            jv = run(["java", "-cp", str(build), "com.wwgateway.verifier.VectorSuite", str(core / "src/test/resources/vectors.json")])
            java = "```\n" + jv.stdout.strip() + "\n```"
        else:
            java = "Java compilation failed:\n```\n" + compiled.stderr[-2000:] + "\n```"

    out = ["# WWGateWay — security report", "", f"Generated {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M UTC} by `tools/security_report.py` from real runs.", ""]
    out += ["## 1. Automated security tests", "", f"Result: `{summary}`", "", "| Suite | Test | Result |", "|---|---|---|"]
    out += [f"| {suite} | `{name}` | {status} |" for suite, name, status in rows]
    out += ["", "## 2. Mutation check (do the tests have teeth?)", "",
            "Each protection is disabled in turn; the suite must fail. `SURVIVED` would mean a protection without a test.", "", "```", mutation.stdout.strip(), "```", ""]
    out += ["## 3. Latency", "", "```", bench.stdout.strip(), "```", "",
            "Issuance includes the HTTP stack, signed-request verification, policy evaluation and the audit write.",
            "Bank-side verification is local (no network call per request).", ""]
    out += ["## 4. Java libraries", "", java,
            "", "The Java verifier is checked against vectors generated by the Python reference (`tools/make_java_vectors.py`).",
            "`GatewayStarterIT` sends every action vector as an HTTP request through a Spring MVC application using the starter",
            "(status code, error code, controller not invoked on rejection) and covers missing tokens, data scoping, the body",
            "size limit, request wrappers, unannotated endpoints and the auto-configuration conditions. `NoSpringJdbcIT` runs",
            "with spring-jdbc removed from the classpath.", ""]
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "SECURITY_REPORT.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote docs/SECURITY_REPORT.md")
    print(summary)


if __name__ == "__main__":
    main()
